name: cloudwalknasa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:

  cupertino_icons:

  audioplayers: ^5.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Since this dependency is not crucial and tha app is small I let then without version
  http:
  logger:
  lottie:
  google_fonts:
  shared_preferences:
  rxdart:
  freezed:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  #load.json
  #claire_de_lune.mp3
  #not_found.json
  #nasa-logo.png
  assets:
    - assets/load.json
    - assets/not_found.json
    - assets/nasa-logo.png
    - assets/songs/claire_de_lune.mp3
    - assets/songs/experience.m4a
  fonts:
    - family: Nasa
      fonts:
        - asset: assets/fonts/nasalization-rg.otf
